#!/usr/bin/env python3

from bs4 import BeautifulSoup
import urllib
import csv

season = '2016'
#base_url = 'http://www.nfl.com/stats/categorystats?archive=true&conference=null&statisticPositionCategory=RUNNING_BACK&season=2016&seasonType=REG&experience=&tabSeq=1&qualified=true&Submit=Go'
base_url = 'http://www.nfl.com/stats/categorystats?archive=true&conference=null&seasonType=REG&experience=&tabSeq=1&qualified=true&Submit=Go'
positions = [ "QUARTERBACK" ,"RUNNING_BACK" ,"WIDE_RECEIVER" ,"TIGHT_END" ,"DEFENSIVE_LINEMAN" ,"LINEBACKER" ,"DEFENSIVE_BACK" ,"KICKOFF_KICKER" ,"KICK_RETURNER" ,"PUNTER" ,"PUNT_RETURNER" ,"FIELD_GOAL_KICKER"]

for p in positions:
  u = base_url + '&season=' + season + '&statisticPositionCategory=' + p
  print("url: %s" % u)
